version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=identity_reconciliation_db
    ports:
      - "5432:5432"
  node-app:
    restart: 'on-failure'
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/identity_reconciliation_db?schema=public
    depends_on:
      - postgres
